cartridge-gg/explorer

bun.lock
src/modules/BlockDetails/page.tsx
src/modules/TransactionDetails/components/CalldataDisplay.tsx
src/modules/TransactionDetails/page.tsx

https://github.com/user-attachments/assets/8e25b903-b3de-479a-a347-0e425d5d9097
https://github.com/user-attachments/assets/337fba9d-08db-4a36-a938-a180babdbfb3

fix: tx details layout

---

src/App.tsx
src/constants/rpc.ts
src/types/types.ts
vite.config.ts

- **base url if embedded**
- **public base path**
- **base path in router**
- **define at build time**

App base path

---

src/modules/HomeNew/SearchBar.tsx

feat: add enter keyboard handler

---

src/shared/components/AccountDisplay.tsx

Show wallet icon and controller username

---

src/shared/components/AccountModal.tsx
src/shared/components/wallet_connect/index.tsx

Automatically connect to the last account

---

src/modules/ClassHash/Deploy.tsx
src/modules/ClassHash/page.tsx
src/shared/components/contract/types.tsx
src/shared/utils/contract.ts

Add deploy contract form

---

bun.lock
package.json
src/modules/HomeNew/SearchBar.tsx
src/services/starknet_provider_config.ts
vite.config.ts

close #58 
Note
- Default dev port is set to 3004
to avoid conflicts with controller. (3001: keychain, 3002:controller-next-example, 3003:profile)
- New `VITE_CARTRIDGE_API_URL` env (default to https://api.cartridge.gg)
- Require cartridge-gg/internal#2884

Search by controller username

---

src/constants/routes.tsx
src/modules/HomeNew/page.tsx
src/modules/JRPC/page.tsx
src/shared/components/accordion/index.tsx
src/shared/hooks/useSpecVersion.tsx

JSON-RPC Playground

---

src/modules/BlockDetails/page.tsx
src/modules/ClassHash/page.tsx
src/modules/ContractDetails/page.tsx
src/modules/HomeNew/SearchBar.tsx
src/modules/JRPC/page.tsx
src/modules/TransactionDetails/page.tsx

This PR adds id to an element in each of the unique pages. The intention for the ids is to be used in testing; as an indicator that the page has been loaded and the elements are rendered correctly.

refactor: unique element id

---

src/shared/components/contract/ReadContractInterface.tsx
src/shared/components/contract/WriteContractInterface.tsx
src/shared/utils/abi.ts

This PR also fixes a crash when non-first input is edited.

Support span array type in input editor

---

src/modules/JRPC/page.tsx
src/shared/components/FunctionInputEditor.tsx

Temporary accept generic string param to comply with Starknet RPC spec

---

src/modules/JsonRpc/page.tsx
src/shared/components/accordion/index.tsx

Fix bottom border of accordion

---

src/modules/ContractDetails/page.tsx
src/shared/components/section/index.tsx

Add link to class hash on contract page

---

src/modules/JsonRpc/page.tsx
src/shared/form/index.tsx

- `cmd | ctrl` + `Enter`: Execute
- `arrow down |  j`: Next method
- `arrow up | k`: Previous method

JSON-RPC key bindings

---

src/shared/components/WalletConnect.tsx

Logic to catch error was missing in #109

Catch user denial and disable auto connect

---

src/modules/Transaction/components/TxType.tsx
src/modules/Transaction/page.tsx

- **fix(transaction): conditionally render components based on tx type**
- **feat(tx): display tx type**

feat(tx): display tx type

---

bun.lock
package.json
src/App.tsx
src/modules/JsonRpc/page.tsx
src/modules/World/hooks.tsx
src/modules/World/page.tsx

Add `/world` page to display Dojo world data indexed by Torii

---

.gitignore
.storybook/preview.tsx
src/shared/components/header/index.tsx
src/shared/components/network.stories.tsx
src/shared/components/network.tsx

Resolves C7E-821
figma: [link](https://www.figma.com/design/OSbzNkyR9UYV4Erz9oF9JJ/%E2%9A%99%EF%B8%8F-Components?node-id=13096-81502&t=QCLMVj4c4DGTN5D3-1)
**Storybook**
- http://localhost:6004/?path=/docs/network-button--docs
| Expectation    | Implementation |
| -------- | ------- |
| ![CleanShot 2025-06-07 at 03 06 35@2x](https://github.com/user-attachments/assets/7debd894-3566-4ca4-a284-780446694794)  | ![CleanShot 2025-06-07 at 03 06 58@2x](https://github.com/user-attachments/assets/519ff177-476f-4110-8423-1194cfd5c125)  |
| ![CleanShot 2025-06-07 at 03 24 43@2x](https://github.com/user-attachments/assets/1b610772-9e30-421b-8fe5-026304765e4c) | ![CleanShot 2025-06-07 at 03 23 34@2x](https://github.com/user-attachments/assets/f78c479a-27d4-4229-abf0-73f3cb21d9d0)    |

feat: network button

---

src/modules/Block/hooks.tsx
src/modules/Block/page.tsx
src/shared/components/data-table.tsx

fix: calculate container height to determine items per page

---

src/modules/Transaction/calldata.tsx
src/shared/components/felt-displayer.tsx

Render calldata dynamically for felt array and json type:
felt array: http://localhost:3004/tx/0x14e19342d12635f9317e0ab4e9cbde56519e178a9c137f4103881e201031d56
json: http://localhost:3004/tx/0x4c1ce429ccfff50f6ad92ddd72a17be9f611736eb8503c50cda98f2c962b983

feat: render calldata dynamically
